"""Academic AI patterns - research paper and essay style slop."""

PATTERNS = [
    {
        "id": "AC-01",
        "category": "academic_thesis",
        "regex": r"this paper argues|this study examines|this research explores|this essay discusses|this article investigates",
        "severity": 0.7,
        "description": "Academic thesis statement",
    },
    {
        "id": "AC-02",
        "category": "academic_findings",
        "regex": r"the findings suggest|results indicate|data show|evidence demonstrates|analysis reveals",
        "severity": 0.6,
        "description": "Research findings statement",
    },
    {
        "id": "AC-03",
        "category": "academic_previous",
        "regex": r"previous research|prior studies|existing literature|earlier work|past scholarship",
        "severity": 0.5,
        "description": "Literature review reference",
    },
    {
        "id": "AC-04",
        "category": "academic_transition",
        "regex": r"\bfurthermore\b|\bmoreover\b|\bin addition,|\bconsequently,|\bnevertheless\b|\bin contrast,|\bsimilarly,",
        "severity": 0.5,
        "description": "Academic transition words (excludes 'however'/'therefore' which are too common in human prose; require trailing comma where ambiguous)",
    },
    {
        "id": "AC-05",
        "category": "academic_conclusion",
        "regex": r"in conclusion|to summarize|in summary|overall|taken together|collectively",
        "severity": 0.6,
        "description": "Academic conclusion marker",
    },
    {
        "id": "AC-06",
        "category": "academic_significance",
        "regex": r"significantly|notably|importantly|crucially|interestingly|surprisingly|remarkably",
        "severity": 0.4,
        "description": "Significance adverb (overused in AI)",
    },
    {
        "id": "AC-07",
        "category": "academic_passive",
        "regex": r"it is argued|it has been shown|it is widely accepted|it should be noted|it is important to",
        "severity": 0.6,
        "description": "Passive voice academic construction",
    },
    {
        "id": "AC-08",
        "category": "academic_method",
        "regex": r"methodology|approach|framework|paradigm|theoretical lens|analytical tool",
        "severity": 0.5,
        "description": "Methodology buzzwords",
    },
    {
        "id": "AC-09",
        "category": "academic_scope",
        "regex": r"broadly speaking|more broadly|in a broader context|on a larger scale|in general",
        "severity": 0.4,
        "description": "Scope broadening phrase",
    },
    {
        "id": "AC-10",
        "category": "academic_limitation",
        "regex": r"it is worth noting|limitations of this study|future research|further investigation|additional work",
        "severity": 0.5,
        "description": "Limitation/future work phrase",
    },
    {
        "id": "AC-11",
        "category": "academic_citation",
        "regex": r"according to|as noted by|as discussed in|building on|drawing from",
        "severity": 0.4,
        "description": "Citation introduction",
    },
    {
        "id": "AC-12",
        "category": "academic_complexity",
        "regex": r"\bmultifaceted\b|\bnuanced\b|\bintricate\b|\bsophisticated\b",
        "severity": 0.5,
        "description": "Complexity adjective cluster (excludes 'complex'/'complicated' — too common in human prose)",
    },
    {
        "id": "AC-13",
        "category": "academic_emphasis",
        "regex": r"it is essential|it is critical|it is vital|it is imperative|it is necessary",
        "severity": 0.5,
        "description": "Emphatic academic construction",
    },
    {
        "id": "AC-14",
        "category": "academic_comparison",
        "regex": r"\bin comparison\b|\bby contrast\b|\bconversely\b|\bon the contrary\b",
        "severity": 0.4,
        "description": "Comparative academic transition (excludes 'while'/'whereas' — too common in human prose)",
    },
    {
        "id": "AC-15",
        "category": "academic_synthesis",
        "regex": r"in light of|given that|considering|in view of|taking into account",
        "severity": 0.4,
        "description": "Synthesis/consideration phrase",
    },
]
