"""Buzzword cluster patterns."""

PATTERNS = [
    {
        "id": "BZ-01",
        "category": "buzzword",
        "regex": r"\bsynergy\b|\bleverage\b|\bparadigm shift\b|\bgame-changer\b",
        "severity": 0.6,
        "description": "Synergy vocabulary",
    },
    {
        "id": "BZ-02",
        "category": "buzzword",
        "regex": r"\bcomprehensive (?:approach|solution|framework|overview|understanding)\b|\bholistic\b|\brobust (?:framework|solution|methodology|approach)\b|\bcutting-edge\b",
        "severity": 0.6,
        "description": "Comprehensiveness buzzword (require context — bare 'robust'/'comprehensive' too common in engineering)",
    },
    {
        "id": "BZ-03",
        "category": "buzzword",
        "regex": r"\btransformative\b|\bgroundbreaking\b|\brevolutionary\b|\binnovative\b",
        "severity": 0.6,
        "description": "Impact theater buzzword",
    },
    {
        "id": "BZ-04",
        "category": "buzzword",
        "regex": r"\bfacilitate\b|\butilize\b|\bimplement solutions\b|\bstrategic\b",
        "severity": 0.6,
        "description": "Process language buzzword",
    },
    {
        "id": "BZ-05",
        "category": "buzzword",
        "regex": r"\bdelve\b|\btapestry\b|\bnuanced understanding\b|\bmultifaceted\b",
        "severity": 0.9,
        "description": "AI self-description buzzword (high confidence)",
    },
    {
        "id": "BZ-06",
        "category": "buzzword",
        "regex": r"\bvalue-added\b|\bhigh-value\b|\bimpactful\b|\bactionable\b",
        "severity": 0.6,
        "description": "Business value buzzword",
    },
    {
        "id": "BZ-07",
        "category": "buzzword",
        "regex": r"\bdisruptive\b|\bscalable\b|\bsustainable\b|\bdata-driven\b",
        "severity": 0.6,
        "description": "Tech startup buzzword",
    },
    {
        "id": "BZ-08",
        "category": "buzzword",
        "regex": r"\bparadigm\b|\b(?:conceptual|theoretical|overarching|guiding|broader) framework\b|\b(?:thriving|complex|interconnected|broader) ecosystem\b|\b(?:evolving|changing|competitive|broader|shifting) landscape\b",
        "severity": 0.6,
        "description": "Abstract system buzzword (require context — bare 'framework'/'ecosystem'/'landscape' too common in tech)",
    },
    {
        "id": "BZ-09",
        "category": "buzzword",
        "regex": r"\bstreamline\b|\boptimize\b|\benhance\b|\bmaximize\b",
        "severity": 0.6,
        "description": "Process improvement buzzword (removed 'leverage' — already in BZ-01)",
    },
    {
        "id": "BZ-10",
        "category": "buzzword",
        "regex": r"\bkey (?:stakeholders?|drivers?|levers?|takeaways?)\b|\bcore competencies?\b",
        "severity": 0.6,
        "description": "Corporate key-item buzzword",
    },
    {
        "id": "BZ-11",
        "category": "buzzword",
        "regex": r"\bsystemic\b|\bmultidimensional\b|\boptimization\b|\bcontinuous improvement\b",
        "severity": 0.6,
        "description": "Corporate process buzzword",
    },
    {
        "id": "BZ-12",
        "category": "buzzword",
        "regex": r"\bpredictive models?\b|\badaptive mechanisms?\b|\borganizational architectures?\b",
        "severity": 0.6,
        "description": "Corporate architecture buzzword",
    },
    {
        "id": "BZ-13",
        "category": "buzzword",
        "regex": r"\bresilience\b|\boperational efficiency\b|\bperformance indicators?\b",
        "severity": 0.6,
        "description": "Corporate performance buzzword",
    },
    {
        "id": "BZ-14",
        "category": "buzzword",
        "regex": r"\bdisruptive innovation\b|\bredefin(?:e|ing) paradigms?\b|\bemerging technologies\b",
        "severity": 0.9,
        "description": "High-confidence AI buzzword",
    },
    {
        "id": "BZ-15",
        "category": "buzzword",
        "regex": r"\banalytical methodologies\b|\bstrategic catalyst\b|\balignment\b",
        "severity": 0.6,
        "description": "Corporate methodology buzzword",
    },
    {
        "id": "BZ-16",
        "category": "buzzword",
        "regex": r"\bforward-looking vision\b|\boriented toward\b|\bshort-term objectives\b",
        "severity": 0.6,
        "description": "Corporate vision buzzword",
    },
]
