"""Conversational AI patterns - neutral ChatGPT/Claude style slop."""

PATTERNS = [
    {
        "id": "CS-01",
        "category": "conversational_setup",
        "regex": r"with the rise of|in today's world|in an era of|in a world where|as we move into",
        "severity": 0.6,
        "description": "Generic contextual setup phrase",
    },
    {
        "id": "CS-02",
        "category": "conversational_simplification",
        "regex": r"it's all about|it comes down to|at its core|at the heart of it|the key is",
        "severity": 0.5,
        "description": "Oversimplification phrase",
    },
    {
        "id": "CS-03",
        "category": "conversational_evolution",
        "regex": r"little by little|gradually|over time|step by step|slowly but surely",
        "severity": 0.4,
        "description": "Gradual evolution marker",
    },
    {
        "id": "CS-04",
        "category": "conversational_generalization",
        "regex": r"those who can|people who|the ones who|those who know how|individuals who",
        "severity": 0.5,
        "description": "Generic human generalization",
    },
    {
        "id": "CS-05",
        "category": "conversational_humility",
        "regex": r"nothing revolutionary|nothing new|not a silver bullet|not a magic solution|no single answer",
        "severity": 0.6,
        "description": "Fake humility / tempered conclusion",
    },
    {
        "id": "CS-06",
        "category": "conversational_accumulation",
        "regex": r"accumulation of small|small steps|tiny changes|small adjustments|little things",
        "severity": 0.5,
        "description": "Incremental progress conclusion",
    },
    {
        "id": "CS-07",
        "category": "conversational_practice",
        "regex": r"in practice|in reality|in fact|the truth is|what actually matters",
        "severity": 0.4,
        "description": "Reality pivot phrase",
    },
    {
        "id": "CS-08",
        "category": "conversational_balance",
        "regex": r"it's about balance|finding the right balance|striking a balance|the sweet spot",
        "severity": 0.5,
        "description": "Balance rhetoric (false equivalence)",
    },
    {
        "id": "CS-09",
        "category": "conversational_ultimately",
        "regex": r"at the end of the day|ultimately|in the end|when all is said and done|in the final analysis",
        "severity": 0.6,
        "description": "Forced concluding transition",
    },
    {
        "id": "CS-10",
        "category": "conversational_adapt",
        "regex": r"adapt to|adjust to|evolve with|keep up with|stay ahead of",
        "severity": 0.4,
        "description": "Adaptation imperative",
    },
    {
        "id": "CS-11",
        "category": "conversational_help",
        "regex": r"helps make|allows us to|enables us to|makes it easier|gives us the ability",
        "severity": 0.4,
        "description": "Capability attribution",
    },
    {
        "id": "CS-12",
        "category": "conversational_neutrality",
        "regex": r"on one hand.*on the other hand|while some.*others|there are pros and cons|it depends on",
        "severity": 0.5,
        "description": "Forced neutrality / both-sidesism",
    },
    {
        "id": "CS-13",
        "category": "conversational_clarity",
        "regex": r"clearly|obviously|undoubtedly|without a doubt|it's clear that",
        "severity": 0.4,
        "description": "Unearned certainty",
    },
    {
        "id": "CS-14",
        "category": "conversational_journey",
        "regex": r"journey|process|path forward|way forward|road ahead",
        "severity": 0.4,
        "description": "Metaphorical journey framing",
    },
    {
        "id": "CS-15",
        "category": "conversational_value",
        "regex": r"what matters most|what really counts|the important thing|the bottom line|the real question",
        "severity": 0.5,
        "description": "Value reframing",
    },
]
