"""Journalist-style AI patterns (implicit transitions, rhetorical questions)."""

PATTERNS = [
    {
        "id": "JR-01",
        "category": "journalist_setup",
        "regex": r"je m'explique|voici pourquoi|regardons de plus près|explications|decryptage",
        "severity": 0.6,
        "description": "FR journalistic setup phrase",
    },
    {
        "id": "JR-02",
        "category": "journalist_setup",
        "regex": r"here'?s why|let me explain|here'?s the thing|the short answer is",
        "severity": 0.6,
        "description": "EN journalistic setup phrase",
    },
    {
        "id": "JR-03",
        "category": "journalist_revelation",
        "regex": r"sauf que|le vrai signal|ce que peu de monde|ce que l'on ne dit pas|l'element cle",
        "severity": 0.7,
        "description": "FR journalistic revelation",
    },
    {
        "id": "JR-04",
        "category": "journalist_revelation",
        "regex": r"except that|the real signal|what few people|what nobody tells you|the key element",
        "severity": 0.7,
        "description": "EN journalistic revelation",
    },
    {
        "id": "JR-05",
        "category": "journalist_rhetorical",
        "regex": r"pourquoi maintenant|qu'est-ce que ca change|et si|imaginez|avez-vous remarque",
        "severity": 0.5,
        "description": "FR rhetorical question",
    },
    {
        "id": "JR-06",
        "category": "journalist_rhetorical",
        "regex": r"why now|what does it change|what if|imagine|have you noticed",
        "severity": 0.5,
        "description": "EN rhetorical question",
    },
    {
        "id": "JR-07",
        "category": "journalist_conclusion",
        "regex": r"ce que ca change|ce que cela signifie|en resume|bilan|a retenir",
        "severity": 0.6,
        "description": "FR journalistic conclusion",
    },
    {
        "id": "JR-08",
        "category": "journalist_conclusion",
        "regex": r"what it means|the takeaway|bottom line|long story short|in short",
        "severity": 0.6,
        "description": "EN journalistic conclusion",
    },
    {
        "id": "JR-09",
        "category": "journalist_implicit",
        "regex": r"c'est ecrit noir sur blanc|on le sait|force est de constater|personne ne peut nier",
        "severity": 0.6,
        "description": "FR implicit assertion",
    },
    {
        "id": "JR-10",
        "category": "journalist_implicit",
        "regex": r"it'?s written in black and white|we know|it goes without saying|nobody can deny",
        "severity": 0.6,
        "description": "EN implicit assertion",
    },
    {
        "id": "JR-11",
        "category": "journalist_direct_address",
        "regex": r"vos\b|votre\b|vous\b|tes\b|ton\b|tu\b|your\b|you\b",
        "severity": 0.4,
        "description": "Direct address to reader (common in AI journalism)",
    },
    {
        "id": "JR-12",
        "category": "journalist_stats_dump",
        "regex": r"\d+[.,]?\d*\s*%|\d+\s*sur\s*\d+|\d+\s*étapes|\d+\s*fois|\d+\s*heures|\d+\s*semaines",
        "severity": 0.5,
        "description": "Statistics dump with percentages and ratios",
    },
    {
        "id": "JR-13",
        "category": "journalist_passive_voice",
        "regex": r"a\s+été\s+\w+é|ont\s+été\s+\w+és|sont\s+\w+és|est\s+\w+é|ont\s+été\s+volontairement|a\s+été\s+volontairement",
        "severity": 0.5,
        "description": "FR passive voice (common in AI-generated text)",
    },
    {
        "id": "JR-14",
        "category": "journalist_anecdote",
        "regex": r"dans\s+\d+\s+.*que\s+je\s+mène|dans\s+mon\s+expérience|je\s+vois\s+souvent|j'ai\s+remarqué",
        "severity": 0.6,
        "description": "Personal anecdote / professional experience claim",
    },
    {
        "id": "JR-15",
        "category": "journalist_observer",
        "regex": r"on\s+a\s+clairement\s+remarqué|on\s+a\s+vu|il\s+est\s+clair\s+que|il\s+est\s+évident",
        "severity": 0.5,
        "description": "Observer assertion pattern",
    },
    {
        "id": "JR-16",
        "category": "journalist_structure",
        "regex": r"\w+\s+\d+\.\d+.*:\s*\d+[.,]?\d*|\d+[.,]?\d+\s*%\s*sur\s*\w+",
        "severity": 0.4,
        "description": "Technical spec listing pattern",
    },
    {
        "id": "JR-17",
        "category": "journalist_implication",
        "regex": r"ce\s+que\s+ça\s+change|ce\s+que\s+cela\s+signifie|ça\s+change\s+tout|ça\s+veut\s+dire",
        "severity": 0.6,
        "description": "FR implication/impact statement",
    },
    {
        "id": "JR-18",
        "category": "journalist_contrast",
        "regex": r"d'un\s+côté|de\s+l'autre|par\s+contre|en\s+revanche|tandis\s+que",
        "severity": 0.4,
        "description": "FR contrast transition",
    },
    {
        "id": "JR-19",
        "category": "journalist_urgency",
        "regex": r"maintenant|aujourd'hui|dès\s+maintenant|il\s+est\s+temps|ne\s+plus\s+attendre",
        "severity": 0.4,
        "description": "Urgency/timeliness marker",
    },
    {
        "id": "JR-20",
        "category": "journalist_en_stats",
        "regex": r"\d+[.,]?\d*\s*%\s*(?:on|of|in|against|vs\.?)|\d+\s*out\s*of\s*\d+|\d+-fold|\d+x\s*faster",
        "severity": 0.5,
        "description": "EN statistics dump pattern",
    },
]
