"""Technical AI patterns - documentation, tutorial, and technical writing slop."""

PATTERNS = [
    {
        "id": "TC-01",
        "category": "technical_intro",
        "regex": r"in this section|in this chapter|in this guide|in this tutorial|in this article",
        "severity": 0.6,
        "description": "Technical section introduction",
    },
    {
        "id": "TC-02",
        "category": "technical_steps",
        "regex": r"the following steps|follow these steps|step by step|first.*then.*finally|to get started",
        "severity": 0.5,
        "description": "Step-by-step instruction marker",
    },
    {
        "id": "TC-03",
        "category": "technical_example",
        "regex": r"for example|for instance|as an example|to illustrate|consider the following",
        "severity": 0.4,
        "description": "Example introduction",
    },
    {
        "id": "TC-04",
        "category": "technical_prerequisite",
        "regex": r"before we begin|prerequisites|requirements|you will need|make sure you have",
        "severity": 0.5,
        "description": "Prerequisite section",
    },
    {
        "id": "TC-05",
        "category": "technical_command",
        "regex": r"run the following|execute this|type the following|copy and paste|enter this command",
        "severity": 0.6,
        "description": "Command instruction",
    },
    {
        "id": "TC-06",
        "category": "technical_explanation",
        "regex": r"as you can see|as shown|as illustrated|as demonstrated|as evidenced by",
        "severity": 0.5,
        "description": "Visual/result reference",
    },
    {
        "id": "TC-07",
        "category": "technical_note",
        "regex": r"\bnote that\b|^\s*(?:warning|caution|tip|note|important):|\bimportant to note\b",
        "severity": 0.4,
        "description": "Callout box marker (anchored — bare 'important' was a major false positive)",
    },
    {
        "id": "TC-08",
        "category": "technical_conclusion",
        "regex": r"in summary|to recap|wrapping up|in closing|to conclude this",
        "severity": 0.5,
        "description": "Technical conclusion",
    },
    {
        "id": "TC-09",
        "category": "technical_next",
        "regex": r"next steps|what's next|moving forward|going further|next up",
        "severity": 0.5,
        "description": "Next steps section",
    },
    {
        "id": "TC-10",
        "category": "technical_benefit",
        "regex": r"benefits of|advantages of|why use|why choose|the main benefit",
        "severity": 0.5,
        "description": "Benefit explanation",
    },
    {
        "id": "TC-11",
        "category": "technical_configuration",
        "regex": r"\bconfiguration (?:options|settings|parameters|file)\b|\bdefault (?:settings|parameters|configuration)\b|\bavailable (?:options|parameters|properties)\b",
        "severity": 0.4,
        "description": "Configuration reference (require multi-word context — bare nouns matched any tech doc)",
    },
    {
        "id": "TC-12",
        "category": "technical_implementation",
        "regex": r"implementation|deploy|install|set up|configure|integrate",
        "severity": 0.5,
        "description": "Implementation action",
    },
    {
        "id": "TC-13",
        "category": "technical_troubleshooting",
        "regex": r"if you encounter|if you see|common issues|troubleshooting|error message",
        "severity": 0.5,
        "description": "Troubleshooting reference",
    },
    {
        "id": "TC-14",
        "category": "technical_performance",
        "regex": r"\bperformance (?:gains?|improvements?|benefits?|metrics?|optimization)\b|\boptimization (?:strategy|techniques?|approach)\b|\bsignificantly (?:faster|improved|reduced)\b",
        "severity": 0.4,
        "description": "Performance metric (require multi-word phrase — bare 'performance'/'optimization' too common)",
    },
    {
        "id": "TC-15",
        "category": "technical_verification",
        "regex": r"\bto verify (?:that|the|your)\b|\bto confirm (?:that|the|your)\b|\bto ensure (?:that|the|your|proper)\b",
        "severity": 0.4,
        "description": "Verification instruction (require object — bare 'to test'/'to check' matched everything)",
    },
]
